=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/root.dtd
<!ELEMENT root (books, authors, genres, roles, users, orders, addresses, reviews, genre_details, author_details, order_details)>

<!-- Book enitity (Thành Trí) -->
<!ELEMENT books (book+)>
<!ELEMENT book (title, page_count, price, amount, publish_year, description, thumbnail, available)>
<!ATTLIST book id ID #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT page_count (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT publish_year (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT thumbnail (#PCDATA)>
<!ELEMENT available (#PCDATA)>

<!-- Author entity (Thế Vinh) -->
<!ELEMENT authors (author*)>
<!ELEMENT author (full_name, date_of_birth, avatar)>
<!ATTLIST author id ID #REQUIRED>
<!ELEMENT full_name (#PCDATA)>
<!ELEMENT date_of_birth (#PCDATA)>
<!ELEMENT avatar (#PCDATA)>

<!-- Genre entity (Thế Vinh) -->
<!ELEMENT genres (genre*)>
<!ATTLIST genre id ID #REQUIRED>
<!ELEMENT genre (genre_name)>
<!ELEMENT genre_name (#PCDATA)>

<!-- Role entity (Quốc Việt) -->
<!ELEMENT roles (role+)>
<!ELEMENT role (role_name)>
<!ATTLIST role id ID #REQUIRED>
<!ELEMENT role_name (#PCDATA)>

<!-- User entity (Quốc Việt) -->
<!ELEMENT users (user+)>

<!ELEMENT user (username, password, numberphone, email, gender)>
<!ATTLIST user id ID #REQUIRED role_id IDREF #REQUIRED>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT numberphone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT roleId (#PCDATA)>

<!-- Order entity (Thành Trí) -->
<!ELEMENT orders (order*)>
<!ELEMENT order (customer_name, tel, order_date, status, order_address, payment_method, discount, total_amount, note?)>
<!ATTLIST order
    id ID #REQUIRED
    customer_id IDREF #REQUIRED
>
<!ELEMENT customer_name (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT order_date (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT order_address (#PCDATA)>
<!ELEMENT payment_method (#PCDATA)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT total_amount (#PCDATA)>
<!ELEMENT note (#PCDATA)>

<!-- Address entity (Quốc Việt) -->
<!ELEMENT addresses (address+)>
<!ELEMENT address (detailed_address, city, ward, default, created_date)>
<!ATTLIST address
    id ID #REQUIRED
    user_id IDREF #REQUIRED>
<!ELEMENT detailed_address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT ward (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT created_date (#PCDATA)>

<!-- Review entity (Quốc Việt) -->
<!ELEMENT reviews (review+)>
<!ELEMENT review (rating, comment, date?)>
<!ATTLIST review id ID #REQUIRED book_id IDREF #REQUIRED user_id IDREF #REQUIRED>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT date (#PCDATA)>

<!-- Genre detail entity (Thế Vinh) -->
<!ELEMENT genre_details (genre_detail*)>
<!ELEMENT genre_detail EMPTY>
<!ATTLIST genre_detail genre_id IDREF #REQUIRED>
<!ATTLIST genre_detail book_id IDREF #REQUIRED>

<!-- Author detail entity (Thế Vinh) -->
<!ELEMENT author_details (author_detail*)>
<!ELEMENT author_detail (author_role)>
<!ELEMENT author_role (#PCDATA)>
<!ATTLIST author_detail author_id IDREF #REQUIRED>
<!ATTLIST author_detail book_id IDREF #REQUIRED>

<!-- Order detail entity (Thành Trí) -->
<!ELEMENT order_details (order_detail*)>
<!ELEMENT order_detail (quantity, unit_price)>
<!ATTLIST order_detail
    id CDATA #REQUIRED
    order_id IDREF #REQUIRED
    book_id IDREF #REQUIRED
>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit_price (#PCDATA)>

=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/root.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "./root.dtd">

<root>
    <!-- Book entity -->
    <books>
        <book id="B001">
            <title>XML Developer's Guide</title>
            <page_count>352</page_count>
            <price>44.95</price>
            <publish_year>2000</publish_year>
            <description>An in-depth look at creating applications
                with XML.</description>
            <thumbnail>xml_developer_guide.jpg</thumbnail>
            <available>true</available>
        </book>

        <book id="B002">
            <title>Midnight Rain</title>
            <page_count>256</page_count>
            <price>5.95</price>
            <publish_year>2001</publish_year>
            <description>A former architect battles corporate zombies,
                an evil sorceress, and her own childhood to become queen
                of the world.</description>
            <thumbnail>midnight_rain.jpg</thumbnail>
            <available>true</available>
        </book>

        <book id="B003">
            <title>Maeve Ascendant</title>
            <page_count>272</page_count>
            <price>5.95</price>
            <publish_year>2000</publish_year>
            <description>After the collapse of a nanotechnology
                society in England, the young survivors lay the
                foundation for a new society.</description>
            <thumbnail>maeve_ascendant.jpg</thumbnail>
            <available>false</available>
        </book>

        <book id="B004">
            <title>Oberon's Legacy</title>
            <page_count>300</page_count>
            <price>5.95</price>
            <publish_year>2001</publish_year>
            <description>In post-apocalypse England, the mysterious
                agent known only as Oberon helps to create a new life
                for the inhabitants of London. Sequel to Maeve
                Ascendant.</description>
            <thumbnail>oberons_legacy.jpg</thumbnail>
            <available>true</available>
        </book>

        <book id="B005">
            <title>The Sundered Grail</title>
            <page_count>400</page_count>
            <price>5.95</price>
            <publish_year>2001</publish_year>
            <description>The two daughters of Maeve, half-sisters,
                battle one another for control of England. Sequel to
                Oberon's Legacy.</description>
            <thumbnail>sundered_grail.jpg</thumbnail>
            <available>false</available>
        </book>

        <book id="B006">
            <title>Lover Birds</title>
            <page_count>150</page_count>
            <price>4.95</price>
            <publish_year>2000</publish_year>
            <description>When Carla meets Paul at an ornithology
                conference, tempers fly as feathers get ruffled.</description>
            <thumbnail>lover_birds.jpg</thumbnail>
            <available>true</available>
        </book>

        <book id="B007">
            <title>Splish Splash</title>
            <page_count>200</page_count>
            <price>4.95</price>
            <publish_year>2000</publish_year>
            <description>A deep sea diver finds true love twenty
                thousand leagues beneath the sea.</description>
            <thumbnail>splish_splash.jpg</thumbnail>
            <available>true</available>
        </book>
    </books>

    <!-- Author entity -->
    <authors>
        <author id="AU001">
            <full_name>Hồ Anh Thái</full_name>
            <date_of_birth>1980-01-01</date_of_birth>
            <avatar>
                https://cand.com.vn/Files/Image/thanhbinh/2020/05/25/thumb_660_f6a85596-232f-4237-a9e6-48c71c477213.JPG
            </avatar>
        </author>
        <author id="AU002">
            <full_name>Nguyễn Vĩnh Nguyên</full_name>
            <date_of_birth>1979-05-01</date_of_birth>
            <avatar> https://www.netabooks.vn/data/author/8331/logo-nguyen-vinh-nguyen.jpg </avatar>
        </author>
        <author id="AU003">
            <full_name>Nguyễn Trương Quý</full_name>
            <date_of_birth>1989-06-04</date_of_birth>
            <avatar>
                https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSwn_mokrmX3dECxWh-T-cM0fEggb4_uZPOQ2KVSx-rJBi7ZnxC3Z_gGYicTMdim8jlRf0A7VtaITCMH845X1eBNCdBQImh7gBWE-Gx-Fc_
            </avatar>
        </author>
        <author id="AU004">
            <full_name>Đỗ Bích Thúy</full_name>
            <date_of_birth>1995-08-05</date_of_birth>
            <avatar> https://vanvn.vn/wp-content/uploads/2021/03/Do-Bich-Thuy-vanvn.jpg </avatar>
        </author>
        <author id="AU005">
            <full_name>Nguyễn Mai Chi</full_name>
            <date_of_birth>1998-04-09</date_of_birth>
            <avatar>
                https://tramvanhoc.com/wp-content/uploads/2024/07/Gioi-thieu-tac-gia-Nguyen-Mai-Chi-Tieu-su-su-nghiep-phong-cach-sang-tac-nhan-dinh.jpg
            </avatar>
        </author>

        <author id="AU006">
            <full_name>Anthony Burgess</full_name>
            <date_of_birth>1917-02-25</date_of_birth>
            <avatar>
                https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRjIEQi65pbyd1sAhVTuuLq1986APk5D_7iw&amp;s
            </avatar>
        </author>
        <author id="AU007">
            <full_name>Maya Angelou</full_name>
            <date_of_birth>1928-04-04</date_of_birth>
            <avatar>
                https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRjjVutIhtrkRs86P8HcPKZm1-gmlb0xexI7ZPTed7g61BZr2lcJBkwAMKdP0x9WSGgVRml-6TU1J3IDcmpTw_KPbxgZnHBEY4trfPRBhDt1w
            </avatar>
        </author>
    </authors>

    <!-- Genre entity -->
    <genres>
        <genre id="G001">
            <genre_name>Tình cảm</genre_name>
        </genre>
        <genre id="G002">
            <genre_name>Tâm lý</genre_name>
        </genre>
        <genre id="G003">
            <genre_name>Học thuật</genre_name>
        </genre>
        <genre id="G004">
            <genre_name>Thiếu nhi</genre_name>
        </genre>
        <genre id="G005">
            <genre_name>Kỹ năng</genre_name>
        </genre>
        <genre id="G006">
            <genre_name>Tiểu thuyết</genre_name>
        </genre>
        <genre id="G007">
            <genre_name>Tài chính</genre_name>
        </genre>
        <genre id="G008">
            <genre_name>Kinh doanh</genre_name>
        </genre>
    </genres>

    <!-- Role entity -->
    <roles>
        <role id="R001">
            <role_name>Admin</role_name>
        </role>
        <role id="R002">
            <role_name>Manager</role_name>
        </role>
        <role id="R003">
            <role_name>Staff</role_name>
        </role>
        <role id="R004">
            <role_name>Employee</role_name>
        </role>
        <role id="R005">
            <role_name>Customer</role_name>
        </role>
    </roles>

    <!-- User entity -->
    <users>
        <user id="U001">
            <username>Lại Trần Thế Vinh</username>
            <password>12345</password>
            <numberphone>0907435567</numberphone>
            <email>vinhltth@gmail.com</email>
            <gender>Nam</gender>
            <roleId>R001</roleId>
        </user>
        <user id="U002">
            <username>Võ Quốc Việt</username>
            <password>12345</password>
            <numberphone>0907313461</numberphone>
            <email>vietvq@gmail.com</email>
            <gender>Nam</gender>
            <roleId>R002</roleId>
        </user>
        <user id="U003">
            <username>Dương Thành Trí</username>
            <password>12345</password>
            <numberphone>0907313462</numberphone>
            <email>dtt@gmail.com</email>
            <gender>Nam</gender>
            <roleId>R003</roleId>
        </user>
        <user id="U004">
            <username>Danh Nhật Tiến</username>
            <password>12345</password>
            <numberphone>0907313463</numberphone>
            <email>dnt@gmail.com</email>
            <gender>Nam</gender>
            <roleId>R004</roleId>
        </user>
        <user id="U005">
            <username>Trần Quang Minh</username>
            <password>12345</password>
            <numberphone>0907313464</numberphone>
            <email>cqm@gmail.com</email>
            <gender>Nam</gender>
            <roleId>R005</roleId>
        </user>
    </users>

    <!-- Order entity -->
    <orders>
        <order id="O001" customer_id="U001">
            <customer_name>John Doe</customer_name>
            <tel>0123456789</tel>
            <order_date>2024-06-15</order_date>
            <status>Processing</status>
            <order_address>123 Main St, Anytown, USA</order_address>
            <payment_method>Credit Card</payment_method>
            <discount>10.4</discount>
            <total_amount>150.75</total_amount>
            <note>Please deliver between 9 AM and 5 PM.</note>
        </order>

        <order id="O002" customer_id="U002">
            <customer_name>Jane Smith</customer_name>
            <tel>9876543210</tel>
            <order_date>2024-06-16</order_date>
            <status>Shipped</status>
            <order_address>456 Elm St, Othertown, USA</order_address>
            <payment_method>PayPal</payment_method>
            <discount>5.0</discount>
            <total_amount>89.50</total_amount>
        </order>

        <order id="O003" customer_id="U003">
            <customer_name>Emily Johnson</customer_name>
            <tel>0123456789</tel>
            <order_date>2024-06-17</order_date>
            <status>Delivered</status>
            <order_address>789 Oak St, Sometown, USA</order_address>
            <payment_method>Credit Card</payment_method>
            <discount>0.0</discount>
            <total_amount>45.00</total_amount>
        </order>

        <order id="O004" customer_id="U003">
            <customer_name>Michael Brown</customer_name>
            <tel>0123456789</tel>
