=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/dtds/danh_gia.dtd
<!ELEMENT reviews (review+)>

<!ELEMENT review (userId, productId, rating, comment, date?)>
<!ATTLIST review
    id ID #REQUIRED>

<!ELEMENT userId (#PCDATA)>
<!ELEMENT productId (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/xmls/danh_gia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reviews SYSTEM "../dtds/danh_gia.dtd">
<reviews>
    <review id="RV001">
        <userId>U005</userId>
        <productId>P001</productId>
        <rating>5</rating>
        <comment>Sản phẩm rất tốt!</comment>
    </review>
    <review id="RV002">
        <userId>U003</userId>
        <productId>P002</productId>
        <rating>4</rating>
        <comment>Chất lượng ổn, giao hàng nhanh.</comment>
        <date>2024-06-15</date>
    </review>
    <review id="RV003">
        <userId>U005</userId>
        <productId>P003</productId>
        <rating>3</rating>
        <comment>Sản phẩm bình thường, không có gì đặc biệt.</comment>
        <date>2024-06-15</date>
    </review>
    <review id="RV004">
        <userId>U003</userId>
        <productId>P004</productId>
        <rating>2</rating>
        <comment>Chất lượng không như mong đợi.</comment>
        <date>2024-06-15</date>
    </review>
    <review id="RV005">
        <userId>U001</userId>
        <productId>P005</productId>
        <rating>1</rating>
        <comment>Rất thất vọng với sản phẩm này.</comment>
        <date>2024-06-15</date>
    </review>
</reviews>
