=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/dtds/nguoi_dung.dtd
<!ELEMENT users (user+)>

<!ELEMENT user (username, password, numberphone, email, gender, roleId)>
<!ATTLIST user
    id ID #REQUIRED>

<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT numberphone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT roleId (#PCDATA)>

=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/xmls/nguoi_dung.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "../dtds/nguoi_dung.dtd">
<users>
    <user id="U001">
        <username>Lại Trần Thế Vinh</username>
        <password>12345</password>
        <numberphone>0907435567</numberphone>
        <email>vinhltth@gmail.com</email>
        <gender>Nam</gender>
        <roleId>R001</roleId>
    </user>
    <user id="U002">
        <username>Võ Quốc Việt</username>
        <password>12345</password>
        <numberphone>0907313461</numberphone>
        <email>vietvq@gmail.com</email>
        <gender>Nam</gender>
        <roleId>R002</roleId>
    </user>
    <user id="U003">
        <username>Dương Thành Trí</username>
        <password>12345</password>
        <numberphone>0907313462</numberphone>
        <email>dtt@gmail.com</email>
        <gender>Nam</gender>
        <roleId>R003</roleId>
    </user>
    <user id="U004">
        <username>Danh Nhật Tiến</username>
        <password>12345</password>
        <numberphone>0907313463</numberphone>
        <email>dnt@gmail.com</email>
        <gender>Nam</gender>
        <roleId>R004</roleId>
    </user>
    <user id="U005">
        <username>Trần Quang Minh</username>
        <password>12345</password>
        <numberphone>0907313464</numberphone>
        <email>cqm@gmail.com</email>
        <gender>Nam</gender>
        <roleId>R005</roleId>
    </user>
</users>
