=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/dtds/sach.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (title, page_count, price, publish_year, description, thumbnail, available)>
<!ATTLIST book id ID #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT page_count (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT publish_year (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT thumbnail (#PCDATA)>
<!ELEMENT available (#PCDATA)>

=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/xmls/sach.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "../dtds/sach.dtd">

<books>
    <book id="B001">
        <title>XML Developer's Guide</title>
        <page_count>352</page_count>
        <price>44.95</price>
        <publish_year>2000</publish_year>
        <description>An in-depth look at creating applications 
        with XML.</description>
        <thumbnail>xml_developer_guide.jpg</thumbnail>
        <available>true</available>
    </book>

    <book id="B002">
        <title>Midnight Rain</title>
        <page_count>256</page_count>
        <price>5.95</price>
        <publish_year>2001</publish_year>
        <description>A former architect battles corporate zombies, 
        an evil sorceress, and her own childhood to become queen 
        of the world.</description>
        <thumbnail>midnight_rain.jpg</thumbnail>
        <available>true</available>
    </book>

    <book id="B003">
        <title>Maeve Ascendant</title>
        <page_count>272</page_count>
        <price>5.95</price>
        <publish_year>2000</publish_year>
        <description>After the collapse of a nanotechnology 
        society in England, the young survivors lay the 
        foundation for a new society.</description>
        <thumbnail>maeve_ascendant.jpg</thumbnail>
        <available>false</available>
    </book>

    <book id="B004">
        <title>Oberon's Legacy</title>
        <page_count>300</page_count>
        <price>5.95</price>
        <publish_year>2001</publish_year>
        <description>In post-apocalypse England, the mysterious 
        agent known only as Oberon helps to create a new life 
        for the inhabitants of London. Sequel to Maeve 
        Ascendant.</description>
        <thumbnail>oberons_legacy.jpg</thumbnail>
        <available>true</available>
    </book>

    <book id="B005">
        <title>The Sundered Grail</title>
        <page_count>400</page_count>
        <price>5.95</price>
        <publish_year>2001</publish_year>
        <description>The two daughters of Maeve, half-sisters, 
        battle one another for control of England. Sequel to 
        Oberon's Legacy.</description>
        <thumbnail>sundered_grail.jpg</thumbnail>
        <available>false</available>
    </book>

    <book id="B006">
        <title>Lover Birds</title>
        <page_count>150</page_count>
        <price>4.95</price>
        <publish_year>2000</publish_year>
        <description>When Carla meets Paul at an ornithology 
        conference, tempers fly as feathers get ruffled.</description>
        <thumbnail>lover_birds.jpg</thumbnail>
        <available>true</available>
    </book>
    
    <book id="B007">
        <title>Splish Splash</title>
        <page_count>200</page_count>
        <price>4.95</price>
        <publish_year>2000</publish_year>
        <description>A deep sea diver finds true love twenty 
        thousand leagues beneath the sea.</description>
        <thumbnail>splish_splash.jpg</thumbnail>
        <available>true</available>
    </book>
</books>
