=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/dtds/tac_gia.dtd
<!ELEMENT authors (author*)>
<!ELEMENT author (full_name, date_of_birth, avatar)>
<!ATTLIST author id ID #REQUIRED>
<!ELEMENT full_name (#PCDATA)>
<!ELEMENT date_of_birth (#PCDATA)>
<!ELEMENT avatar (#PCDATA)>

=== lai-tran-the-vinh/nhom-12-he-thong-ban-sach-online/xmls/tac_gia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authors SYSTEM "../dtds/tac_gia.dtd">

<authors>
    <author id="A001">
        <full_name>Hồ Anh Thái</full_name>
        <date_of_birth>1980-01-01</date_of_birth>
        <avatar>
            https://cand.com.vn/Files/Image/thanhbinh/2020/05/25/thumb_660_f6a85596-232f-4237-a9e6-48c71c477213.JPG
        </avatar>
    </author>
    <author id="A002">
        <full_name>Nguyễn Vĩnh Nguyên</full_name>
        <date_of_birth>1979-05-01</date_of_birth>
        <avatar> https://www.netabooks.vn/data/author/8331/logo-nguyen-vinh-nguyen.jpg </avatar>
    </author>
    <author id="A003">
        <full_name>Nguyễn Trương Quý</full_name>
        <date_of_birth>1989-06-04</date_of_birth>
        <avatar>
            https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSwn_mokrmX3dECxWh-T-cM0fEggb4_uZPOQ2KVSx-rJBi7ZnxC3Z_gGYicTMdim8jlRf0A7VtaITCMH845X1eBNCdBQImh7gBWE-Gx-Fc_
        </avatar>
    </author>
    <author id="A004">
        <full_name>Đỗ Bích Thúy</full_name>
        <date_of_birth>1995-08-05</date_of_birth>
        <avatar> https://vanvn.vn/wp-content/uploads/2021/03/Do-Bich-Thuy-vanvn.jpg </avatar>
    </author>
    <author id="A005">
        <full_name>Nguyễn Mai Chi</full_name>
        <date_of_birth>1998-04-09</date_of_birth>
        <avatar>
            https://tramvanhoc.com/wp-content/uploads/2024/07/Gioi-thieu-tac-gia-Nguyen-Mai-Chi-Tieu-su-su-nghiep-phong-cach-sang-tac-nhan-dinh.jpg
        </avatar>
    </author>

    <author id="A006">
        <full_name>Anthony Burgess</full_name>
        <date_of_birth>1917-02-25</date_of_birth>
        <avatar>
            https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRjIEQi65pbyd1sAhVTuuLq1986APk5D_7iw&amp;s
        </avatar>
    </author>
    <author id="A007">
        <full_name>Maya Angelou</full_name>
        <date_of_birth>1928-04-04</date_of_birth>
        <avatar>
            https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRjjVutIhtrkRs86P8HcPKZm1-gmlb0xexI7ZPTed7g61BZr2lcJBkwAMKdP0x9WSGgVRml-6TU1J3IDcmpTw_KPbxgZnHBEY4trfPRBhDt1w
        </avatar>
    </author>
</authors>
